

-------------------------------------------------------------------------
Systeminfo:
CPU:               Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Number of CPUs:    8
RAM:               31.9GB
Diskinfo:          26.9GB/446.5GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 30.10.2024 16:37:04 (UTC +0:00) === ecu.test 2024.3.0.156114+c108ea21784a 156114+c108ea21784a (2024/09/19 12:15:31) (64bit) ===
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] / wx: 4.2.1+tt.5
Protocol: log level Default. Additional logging active: default output

License: ecu.test
         - License options:
             + ecu.test diagnostics
         - valid up to version: 2024.4
         - valid until: 2025-01-28
         - licensed for: Mahindra_Racing_UK
         - runner: False
         - Server: license01.tracetronic.de



2024-10-30 16:37:04.912 9080 ManagedWorker-1*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1229, in Port
                          File "tts\core\toolingFramework\toolAccess\Binding.py", line 459, in GetPort
                          File "tts\core\toolingFramework\toolAccess\BindingBase.py", line 113, in GetPortBinding
                        tts.core.toolingFramework.toolAccess.Exceptions.IdException: Invalid port-ID: BUS01
                        
                        During handling of the above exception, another exception occurred:
                        
                        Traceback (most recent call last):
                          File "tts\core\package\engine\ExecutionMappingSpaceManager.py", line 558, in __CallRegisterXaObjects
                          File "tts\testModule\bus\mapping\XABusSignalVariableExec.py", line 24, in PrepareWrite
                          File "tts\core\mapping\xa\XAVariableExec.py", line 91, in GetPort
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1232, in Port
                        tts.core.toolingFramework.testbenchConfig.Testbench.TestbenchError: Port not available or not connected: BUS01
