

-------------------------------------------------------------------------
Systeminfo:
CPU:               Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Number of CPUs:    8
RAM:               31.9GB
Diskinfo:          18.9GB/446.5GB
Operating system:  Windows-10-10.0.19045
Long path support: False
-------------------------------------------------------------------------

= 03.11.2024 15:47:23 (UTC +0:00) === ecu.test 2024.3.0.156114+c108ea21784a 156114+c108ea21784a (2024/09/19 12:15:31) (64bit) ===
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] / wx: 4.2.1+tt.5
Protocol: log level Default. Additional logging active: default output

License: ecu.test
         - License options:
             + ecu.test diagnostics
         - valid up to version: 2024.4
         - valid until: 2025-01-28
         - licensed for: Mahindra_Racing_UK
         - runner: False
         - Server: license01.tracetronic.de



2024-11-03 15:47:23.244 15240 ManagedWorker-5*PE.Run() ERROR:
                        Traceback (most recent call last):
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1229, in Port
                          File "tts\core\toolingFramework\toolAccess\Binding.py", line 459, in GetPort
                          File "tts\core\toolingFramework\toolAccess\BindingBase.py", line 113, in GetPortBinding
                        tts.core.toolingFramework.toolAccess.Exceptions.IdException: Invalid port-ID: NULL-DEFAULT01
                        
                        During handling of the above exception, another exception occurred:
                        
                        Traceback (most recent call last):
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 186, in __Call
                          File "tts\core\mapping\xa\XAJobExec.py", line 83, in Call
                          File "tts\core\mapping\xa\XAJobExec.py", line 40, in _GetExecContext
                          File "tts\core\toolingFramework\testbenchConfig\Testbench.py", line 1232, in Port
                        tts.core.toolingFramework.testbenchConfig.Testbench.TestbenchError: Port not available or not connected: NULL-DEFAULT01
2024-11-03 15:47:23.281 15240 ManagedWorker-5*PE.Run() DEBUG_EXC_PRINT:
                        Traceback (most recent call last):
                          File "tts\testExecution\engine\TestEngine.py", line 923, in ExecuteTestStep
                          File "tts\testExecution\testSteps\generic\TestStepJobExec.py", line 265, in Run
                        tt._Exceptions_.TTError: Port not available or not connected: NULL-DEFAULT01
